name: flutter_map
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  image_picker: ^0.8.5+3
  path_provider: ^2.0.10
  path: ^1.8.0
  cupertino_icons: ^1.0.2
  location: ^4.4.0
  google_maps_flutter: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
